version: '3.2'

services:
  php.service:
    build:
      context: './phpapache/'
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: php.container
    volumes:
      - ../../DEV/web-apps/:/var/www/html/
      - ./phpapache/vhost/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "${APACHE_HTTP_PORT}:80"
    stdin_open: true
    tty: true
networks:
  default:
    external: true #needs to be created by other file
    name: mysql_default